import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Share/Navbar";
import { Providers } from "../Provider/Providers";
import Footer from "@/Components/Share/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" suppressHydrationWarning={true}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning={true}>
        <Providers>
          <Navbar />
          <main className="container mx-auto ">
            {children}
          </main>
          <Footer />
          
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
        </Providers>


      </body>
    </html>
  );
}
